---
# This playbook uses the win_get_url module to download a simple HTML file for IIS
- name: Download simple web site 
  hosts: webservers

  gather_facts: false
  tasks:
  - name: Download simple web site to 'C:\inetpub\wwwroot\ansible.html'
    win_get_url:
      url: 'https://raw.githubusercontent.com/fvzwieten/website_acme/master/index.php'
      dest: 'C:\inetpub\wwwroot\ansible.html'
